config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, :skip => [:registrations]
  resources :users

  as :user do
    get 'edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  resources "wedding-albums", :controller => :wedding_albums, :as => :wedding_albums, param: :title
  resources "baptism-albums", :controller => :baptism_albums, :as => :baptism_albums, param: :title
  resources "interior-albums", :controller => :interior_albums, :as => :interior_albums, param: :title


  resources :faqs
  resources :testimonials

  root 'basic_pages#index'
  get 'basic_pages/index'
  get 'about', to: 'basic_pages#about'
  get 'contact', to: 'basic_pages#contact'
  post 'thank-you', to: 'basic_pages#thank_you'
  get 'frequently-asked-questions', to: 'basic_pages#faq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_faq.html.erb
<div class="card">
  <% if user_signed_in? %>
    <button class="btn card-header editable collapsed" id="heading<%= faq.id %>" data-toggle="collapse" data-target="#collapse<%= faq.id %>" aria-expanded="false" aria-controls="collapse<%= faq.id %>">
  <% else %>
    <button class="btn card-header collapsed" id="heading<%= faq.id %>" data-toggle="collapse" data-target="#collapse<%= faq.id %>" aria-expanded="false" aria-controls="collapse<%= faq.id %>">
  <% end %>
      <div class="row">
        <span class="col-1 fa-stack p-0" id="camera">
          <i class="fas fa-camera fa-stack-1x fa-lg"></i>
          <i class="fas fa-haykal fa-stack-2x" id="flash"></i>
        </span>
        <h5 class="col-11 mb-0"><%=faq.question %></h5>
        <% if user_signed_in? && (not request.url.include? "frequently_asked_questions") %>
          <div class="links-index col-12">
            <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_faq_path(faq) %>
            <%= link_to '<i class="fa fa-trash-o" ></i>'.html_safe, faq, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div> <!-- end links-index -->
         <% end %>
      </div>
  </button>

  <div id="collapse<%= faq.id %>" class="collapse" aria-labelledby="heading<%= faq.id %>">
    <div class="col-md-11 offset-md-1 card-body"><%= faq.answer %></div>
  </div>
</div>

app/views/faqs/_form.html.erb
<%= form_with(model: faq, local: true) do |f| %>
  <% if faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% faq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %>
    <%= f.text_area :question, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :answer %>
    <%= f.text_area :answer, rows: 10, class: 'form-control' %>
  </div>

  <div class="actions">
    <% if faq.persisted? %>
      <%= f.submit "Update question", class: "btn" %>
      <%= link_to "Cancel", faq, class: "btn", data: { confirm: "Editing will be canceled. No changes will be saved. Are you sure?"} %>

    <% else %>
      <%= f.submit "Create question", class: "btn" %>
      <%= link_to "Cancel", faqs_path, class: "btn", data: { confirm: "Editing will be canceled. No changes will be saved. Are you sure?"} %>
    <% end %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<div class="container form">
  <h1 class="text-center">Editing FAQs</h1>

  <%= render 'form', faq: @faq %>

</div>

app/views/faqs/index.html.erb
<div class="container-fluid faq">
  <h1 class="text-center">Frequently Asked Questions</h1>

  <div id="accordion">
    <%= render @faqs %>
  </div> <!-- end accordion -->

</div> <!-- end container -->

<div class="container">
  <% if user_signed_in? %>
    <div class="row new-faq">
      <%= link_to 'New Question', new_faq_path, class: "btn col-10 offset-1" %>
    </div>
  <% end %>
</div>

app/views/faqs/new.html.erb
<div class="container form">
  <h1 class="text-center">New Question</h1>

  <%= render 'form', faq: @faq %>

</div>

app/views/faqs/show.html.erb
<div class="container">

  <p>
    <strong>Question:</strong>
    <%= @faq.question %>
  </p>

  <p>
    <strong>Answer:</strong>
    <%= @faq.answer %>
  </p>

  <div class="links">
    <div class="row">
      <div class="col col-10 offset-1 col-md-5 offset-md-0">
        <%= link_to 'Edit qestion',edit_faq_path(@faq), class: "btn" %>
      </div>
      <div class="col col-10 offset-1 col-md-3 offset-md-0">
        <%= link_to 'Delete question'.html_safe, @faq, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-red" %>
      </div>
      <div class="col col-10 offset-1 col-md-4 offset-md-0">
        <%= link_to "Show all FAQs", faqs_path, class: "btn" %>
      </div>
    </div>
  </div>

</div>