config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, :skip => [:registrations]
  resources :users

  as :user do
    get 'edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  resources "wedding-albums", :controller => :wedding_albums, :as => :wedding_albums, param: :title
  resources "baptism-albums", :controller => :baptism_albums, :as => :baptism_albums, param: :title
  resources "interior-albums", :controller => :interior_albums, :as => :interior_albums, param: :title


  resources :faqs
  resources :testimonials

  root 'basic_pages#index'
  get 'basic_pages/index'
  get 'about', to: 'basic_pages#about'
  get 'contact', to: 'basic_pages#contact'
  post 'thank-you', to: 'basic_pages#thank_you'
  get 'frequently-asked-questions', to: 'basic_pages#faq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  def self.english_testimonials
    Testimonial.where(language_id: 1)
  end

  def self.greek_testimonials
    Testimonial.where(language_id: 2)
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: 'Testimonial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:signature, :testimonial_on, :description, :photo, :language_id, :date_exists, :remove_photo )
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= form_with(model: testimonial, local: true) do |f| %>
  <% if testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% testimonial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="with-border">
    <div class="field">
      <%= f.label :language_id, "Select language:" %>
      <% if testimonial.persisted? %>
        <%= f.select :language_id, options_for_select([['English', 1], ['Greek', 2]], testimonial.language_id) %>
      <% else %>
        <%= f.select :language_id, options_for_select([['English', 1], ['Greek', 2]]) %>
      <% end %>
    </div>

    <div class="field testimonial-signature">
      <%= f.label :signature, "Signature" %>
      <%= f.text_field :signature, class: 'form-control'  %>
    </div>

    <div class="field">
      <%= f.label :testimonial_on %>
      <%= f.date_select :testimonial_on, start_year: 2000, class: 'form-control date-box'%>
      <%= f.check_box :date_exists, {id: "date-exists-cb"}, false, true %>
      <%= f.label :date_exists, "Do not specify date" %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 15, class: 'form-control'  %>
    </div>
  </div>

  <div class="field with-border">
    <% if testimonial.photo? %>
      <p>Photo (square)</p>
      <div class="row uploaded-cover-photo">
        <div class="col-3 col-md-2">
          <%= image_tag( testimonial.photo.url.to_s , class: "img-fluid", alt: testimonial.photo_identifier.to_s) %>
        </div>
        <div class="col-7 col-md-10">
          <p><b>Uploaded photo:</b> <%= testimonial.photo %></p>
          <label>
            <%= f.check_box :remove_photo %>
            Delete uploaded photo
          </label>
        </div>
      </div><br/>
      <%= f.label :photo, "<span><b>Replace</b> photo</span>".html_safe %>
    <% else %>
      <%= f.label :photo, "Photo (square)" %>
    <% end %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <% if testimonial.persisted? %>
      <%= f.submit "Update testimonial", class: "btn" %>
      <%= link_to "Cancel editing", testimonial, class: "btn", data: { confirm: "Editing will be canceled. No changes will be saved. Are you sure?"} %>

    <% else %>
      <%= f.submit "Create testimonial", class: "btn" %>
      <%= link_to "Cancel", testimonials_path, class: "btn", data: { confirm: "Editing will be canceled. No changes will be saved. Are you sure?"} %>
    <% end %>
  </div>
<% end %>

app/views/testimonials/_testimonial.html.erb
<div class="card">
  <div class="row">
    <div class="col-md-3">
      <% if testimonial.photo? %>
        <%= image_tag(testimonial.photo.url.to_s , class: "img-fluid", alt: "Theofilos Venardos Photography: #{testimonial.signature} photo") %>
      <% end %>
      <p class="signature"><%= testimonial.signature %></p>
      <p class="date"><%= testimonial.testimonial_on.strftime("%d/%m/%Y")  %></p>
    </div>
    <div class="col-md-9 testimonial">
      <% if testimonial.language_id == 1 %>
        <p><%= testimonial.description %></p>
      <% else %>
        <p class="font-gr"><%= testimonial.description %></p>
      <% end %>

    </div>
  </div> <!-- end row -->

  <% if not (current_page?(root_url)) || (request.url.include? "index") %>
    <div class="links-index col-12">
      <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_testimonial_path(testimonial) %>
      <%= link_to '<i class="fa fa-trash-o" ></i>'.html_safe, testimonial, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div> <!-- end links-index -->
   <% end %>
</div> <!-- end card -->

app/views/testimonials/edit.html.erb
<div class="container form">
  <h1 class="text-center">Editing Testimonial</h1>

  <%= render 'form', testimonial: @testimonial %>

</div>

app/views/testimonials/index.html.erb
<div class="container testimonials text-center">

  <h1>Testimonials</h1>

  <% @testimonials.each do |testimonial| %>
    <%= link_to testimonial, :action => 'go' do %>
      <%= render testimonial %>
    <% end %>
  <% end %>

  <div class="row">
    <%= link_to 'New Testimonial', new_testimonial_path, class: "btn col-12" %>
  </div>

</div>

app/views/testimonials/new.html.erb
<div class="container form">
  <h1 class="text-center">New Testimonial</h1>

  <%= render 'form', testimonial: @testimonial %>

</div>

app/views/testimonials/show.html.erb
<div class="container testimonial text-center">
  <div class="row">
    <div class="col-10 offset-1 col-md-6 offset-md-3">
      <%= image_tag(@testimonial.photo.url.to_s , class: "img-fluid", alt: @testimonial.signature) %>
      <p class="signature"><%= @testimonial.signature %></p>
      <p class="date"><%= @testimonial.testimonial_on.strftime("%d/%m/%Y")  %></p>
    </div>
  </div>
  <% if @testimonial.language_id == 1 %>
    <p><%= @testimonial.description %></p>
  <% else %>
    <p class="font-gr"><%= @testimonial.description %></p>
  <% end %>

  <div class="links">
    <div class="row">
      <div class="col col-10 offset-1 col-md-5 offset-md-0">
        <%= link_to 'Edit testimonial',edit_testimonial_path(@testimonial), class: "btn" %>
      </div>
      <div class="col col-10 offset-1 col-md-3 offset-md-0">
        <%= link_to 'Delete testimonial'.html_safe, @testimonial, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-red" %>
      </div>
      <div class="col col-10 offset-1 col-md-4 offset-md-0">
        <%= link_to "Show all testimonials", testimonials_path, class: "btn" %>
      </div>
    </div>
  </div>

</div>