config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, :skip => [:registrations]
  resources :users

  as :user do
    get 'edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end


  resources "wedding-albums", :controller => :wedding_albums, :as => :wedding_albums, param: :title
  resources "baptism-albums", :controller => :baptism_albums, :as => :baptism_albums, param: :title
  resources "interior-albums", :controller => :interior_albums, :as => :interior_albums, param: :title


  resources :faqs
  resources :testimonials

  root 'basic_pages#index'
  get 'basic_pages/index'
  get 'about', to: 'basic_pages#about'
  get 'contact', to: 'basic_pages#contact'
  post 'thank-you', to: 'basic_pages#thank_you'
  get 'frequently-asked-questions', to: 'basic_pages#faq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.present?
      can [:show, :update, :destroy], User, id: user.id
      can :manage, WeddingAlbum
      can :manage, BaptismAlbum
      can :manage, InteriorAlbum
      can :manage, Testimonial
      can :manage, Faq
      if user.admin?
        can :manage, :all
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baptism_album.rb
class BaptismAlbum < ApplicationRecord
  has_many :baptism_album_translations, dependent: :destroy, inverse_of: :baptism_album
  has_many :baptism_photos, dependent: :destroy, inverse_of: :baptism_album

  accepts_nested_attributes_for :baptism_album_translations, allow_destroy: true
  accepts_nested_attributes_for :baptism_photos, allow_destroy: true, reject_if: :all_blank

  mount_uploader :photo, PhotoUploader
  mount_uploader :photo_square, PhotoUploader

  def to_param
    self.baptism_album_translations.first.title.downcase.tr(" ","-").gsub("&","and")
  end
end

app/models/baptism_photo.rb
class BaptismPhoto < ApplicationRecord
  belongs_to :baptism_album, optional: true
  mount_uploader :photo, PhotoUploader
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/interior_album.rb
class InteriorAlbum < ApplicationRecord
  has_many :interior_album_translations, dependent: :destroy, inverse_of: :interior_album
  has_many :interior_photos, dependent: :destroy, inverse_of: :interior_album

  accepts_nested_attributes_for :interior_album_translations, allow_destroy: true
  accepts_nested_attributes_for :interior_photos, allow_destroy: true, reject_if: :all_blank

  mount_uploader :photo, PhotoUploader
  mount_uploader :photo_square, PhotoUploader

  def to_param
    self.interior_album_translations.first.title.downcase.tr(" ","-").gsub("&","and")
  end

end

app/models/interior_photo.rb
class InteriorPhoto < ApplicationRecord
  belongs_to :interior_album, optional: true
  mount_uploader :photo, PhotoUploader
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :wedding_album_translations

end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  def self.english_testimonials
    Testimonial.where(language_id: 1)
  end

  def self.greek_testimonials
    Testimonial.where(language_id: 2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/wedding_album.rb
class WeddingAlbum < ApplicationRecord

  has_many :wedding_album_translations, dependent: :destroy, inverse_of: :wedding_album
  has_many :wedding_photos, dependent: :destroy, inverse_of: :wedding_album

  accepts_nested_attributes_for :wedding_album_translations, allow_destroy: true
  accepts_nested_attributes_for :wedding_photos, allow_destroy: true, reject_if: :all_blank

  mount_uploader :photo, PhotoUploader
  mount_uploader :photo_square, PhotoUploader

  def to_param
    self.wedding_album_translations.first.title.downcase.tr(" ","-").gsub("&","and")
  end

end

app/models/wedding_photo.rb
class WeddingPhoto < ApplicationRecord
  belongs_to :wedding_album, optional: true
  mount_uploader :photo, PhotoUploader

end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    # admins only
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baptisms_helper.rb
module BaptismsHelper
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- Should be really the first thing in the <head> -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156495058-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-156495058-2');
    </script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title><%= yield(:title) %></title>
    <meta name="description" content="Wedding, Bapthism and Interior Design Photographer. Professional Photo Shoots in Athens, throughout Greece and abroad.">
    <!-- <meta name="description" content="Φωτογράφος Γάμου, Βάφτισης και Εσωτερικού Χώρου. Καλλιτεχνικές φωτογραφίσεις στην Αθήνα, σε όλη την Ελλάδα και στο Εξωτερικό."> -->
    <meta name="keywords" content="Φωτογράφος, φωτογράφος γάμου, φωτογράφος βάφτιστης, φωτογράφος εσωτερικού χώρου, ΑΘήνα, Ελλάδα, Νησιά, Εξωτερικό, Photography, photographer, Wedding, Baptism, Interior Design, Athens, Greece, greek islands">
    <meta name="image" content='<%= image_tag( "https://theofilosvenardos.com/meta_images/meta_image_1.jpg" , alt: "Theofilos Venardos Photography") %>'>

    <!-- Facebook meta tags -->
    <meta property="og:title" content="Theofilos Venardos Photography" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.theofilosvenardos.com" />
    <meta property="og:image" content="https://theofilosvenardos.com/meta_images/meta_image_1.jpg">
    <meta property="og:image:alt" content="Theofilos Venardos Wedding Photography" />
    <meta property="og:description" content="Professional wedding, baptism and interior design photography." />

    <!-- Favicon Tag -->
    <%= favicon_link_tag asset_path('favicon.png') %>

    <!-- Canonical Tag -->
    <link rel="canonical" href="https://theofilosvenardos.com"/>


    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Javascript -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

    <!-- Google Fonts API -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,500,600|Open+Sans|Roboto|Roboto+Slab:300,400|Didact+Gothic" rel="stylesheet">

    <!-- Font Awesome 5 Icons -->
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.6.3/css/all.css' integrity='sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/' crossorigin='anonymous'>
    <!-- Font Awesome 4 Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Google Structed Data -->
    <script type='application/ld+json'>
      {
        "@context": "http://www.schema.org",
        "@type": "ProfessionalService",
        "name": "Theofilos Venardos Photography",
        "url": "https://www.theofilosvenardos.com",
        "logo": "https://theofilosvenardos.com/favicon.png",
        "image":[
          "https://theofilosvenardos.com/meta_images/meta_image_1.jpg",
          "https://theofilosvenardos.com/meta_images/meta_image_2.jpg",
          "https://theofilosvenardos.com/meta_images/meta_image_3.jpg",
          "https://theofilosvenardos.com/meta_images/meta_image_4.jpg"
        ],
          "description": "Φωτογράφος Γάμου, Βάφτισης και Εσωτερικού Χώρου. Καλλιτεχνικές φωτογραφίσεις στην Αθήνα, σε όλη την Ελλάδα και στο Εξωτερικό.",
        "address": {
           "@type": "PostalAddress",
           "addressLocality": "Athens",
           "addressCountry": "GR"
        },
        "telephone": "+30 697 6769195",
        "sameAs": [
            "https://www.facebook.com/VenardosPhotography",
            "https://www.instagram.com/theofilos_venardos/"
            ]
      }
    </script>
  </head>


  <body>
    <!--navbar starts here-->
    <nav class="navbar navbar-light navbar-expand-md bg-light justify-content-md-center fixed-top">
      <%= link_to "Theofilos Venardos", root_url, class: "navbar-brand d-md-none" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="collapsingNavbar">
        <ul class="navbar-nav mx-auto text-md-center text-left">
          <li class="nav-item dropdown">
            <a class="nav-link navbarDropdown" href="#" id="navbarDropdown-portfolio" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              PORTFOLIO <i class='fas fa-angle-down fa-lg'></i>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
             <%= link_to "Weddings", wedding_albums_path, class: "dropdown-item" %>
             <%= link_to "Baptism", BaptismAlbum.first, class: "dropdown-item" %>
             <%= link_to "Interior Design", InteriorAlbum.first, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item <%= 'active' if current_page?(about_path) %>"><%= link_to "ABOUT", about_path, class: "nav-link" %></li>
          <li class="nav-item my-auto">
            <%= link_to "Theofilos Venardos", root_url, class: "nav-link navbar-brand mx-0 d-none d-md-inline" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(frequently_asked_questions_path) %>"><%= link_to "FAQ", frequently_asked_questions_path, class: "nav-link" %></li>
          <li class="nav-item <%= 'active' if current_page?(contact_path) %>"><%= link_to "CONTACT", contact_path, class: "nav-link" %></li>
        </ul>
        <ul class="navbar-nav flex-row justify-content-md-center justify-content-start user-link">
          <% if user_signed_in? %>
            <% user_name = "User" %>
            <% if current_user.name? %>
              <% user_name = current_user.name %>
            <% end %>
            <li class="nav-item dropdown w-100">
              <a class="nav-link navbarDropdown" href="#" id="navbarDropdown-user" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Hi <%= user_name %> <i class='fas fa-angle-down fa-lg'></i>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <!-- <div class="dropdown-divider"></div> -->
                <%= link_to "Manage Weddings", wedding_albums_path, class: "dropdown-item" %>
                <%= link_to "Manage Baptisms", baptism_albums_path, class: "dropdown-item" %>
                <%= link_to "Manage Interior Design", interior_albums_path, class: "dropdown-item" %>
                <%= link_to "Manage Testimonials", testimonials_path, class: "dropdown-item" %>
                <%= link_to "Manage FAQs", faqs_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "My Account", current_user, method: :get, class: "dropdown-item" %>
                <% if current_user.admin? %>
                  <%= link_to "Manage Users", users_path, method: :get, class: "dropdown-item" %>
                <% end %>
                <div class="dropdown-divider"></div>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <!-- navbar ends here -->

    <!-- main body starts here -->
    <div class="anchor">
      <!-- flash messages -->
      <div class="container flash-messages">
        <% if notice %>
          <p id="notice" class="alert alert-info", role="alert"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p id="alert" class="alert alert-danger", role="alert"><%= alert %></p>
        <% end %>
      </div>

      <div class="main-body">
        <%= yield %>
      </div>
    </div>
    <!-- main body ends here -->

    <!-- footer starts here -->
    <footer>
      <div class="container-fluid" id="footer">
        <!-- Instagram starts here -->
        <% if true %>
        <div class="instagram text-center">
        <h2>FOLLOW ME ON INSTAGRAM</h2>
        <div class="instagram-link">
          <%= link_to "#theofilosvenardosphotography", "https://www.instagram.com/theofilos_venardos/",  target: "_blank" %>
        </div>
        <div class="instagram-photos">
          <div class="row">
            <% @instagram_media_url.each_with_index do |media_url, index| %>
              <% if index.even? %>
                <div class="col-4 offset-2 col-sm-2 offset-sm-0 instagram-photo">
              <% else %>
                <div class="col-4 col-sm-2 instagram-photo">
              <% end %>
                <%= link_to @instagram_links[index], :action => 'go', target: "_blank"  do %>
                  <%= image_tag(media_url, class: "img-fluid", alt: "#theofilosvenardosphotography") %>
                <% end %>
                </div>
            <% end %>
          </div> <!-- end row -->
        </div>
      </div> <!-- end instagram -->
      <% end %>

      <div class="content">
        <div class="row">
          <div class="col-md-4 social-media">
            <%= link_to "<i class='fab fa-facebook-f fa-sm'></i>".html_safe, "https://www.facebook.com/VenardosPhotography",  target: "_blank" %>
            <%= link_to "<i class='fab fa-instagram fa-sm'></i>".html_safe, "https://www.instagram.com/theofilos_venardos/",  target: "_blank" %>
            <%= link_to "<i class='fas fa-envelope fa-sm'></i>".html_safe, contact_path %>
          </div>
          <div class="col-md-4 logo text-center">
            <p>Theofilos Venardos</p>
          </div>
          <div class="col-md-4 copyright text-center">
            <p>&copy; 2019 - <%= Date.today.year %> Theofilos Venardos</p>
          </div>
        </div> <!-- end row -->
      </div> <!-- end content -->

      </div> <!-- end container-fluid -->
    </footer>
    <!-- footer ends here -->
  </body>
</html>